### ISSUE TITLE
Meta issue on things to parse

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/MoosePy#15]
I'll use this issue as a todo list. Was is checked are things with a test in project1

- [x] Split visitor into two. One to create entities and one to do the resolution
- [x] Error handling to not stop the import
- [x] Skippable #tryToResolveInScope 
- [ ] Manage private entities
- [ ] Heritage multiple
- [x] Model
  - [x] Name
  - [x] Root folder
  - [x] Source language
- [x] Source anchor
  - [x] Start/end
  - [x] Complete text
  - [x] Root folder
- [ ] Packages 
  - [x] Name
  - [x] Source anchor
  - [x] Root
  - [x] Subpackages
  - [ ] Stubs (from imports)
  - [ ] Two stubs of the same name
- [ ] Namespace packages 
- [x] Modules
  - [x] Name
  - [x] Module at Root
  - [x] Module in package
  - [x] Source anchor
  - [x] 2 modules of the same name in different packages
- [x] Comments
  - [x] Single line 
    - [x] In modules
    - [x] In packages
    - [x] In classes
    - [x] In methods
    - [x] In functions
    - [x] Before classes
    - [x] Before functions
    - [x] Before methods
    - [x] Before global
    - [x] Before ivar
    - [x] Before locale
    - [x] After global
    - [x] After ivar
    - [x] After locale
    - [x] Merge simple line comments following each other
  - [x] Multiple line comments using a String
    - [x] In modules
    - [x] In packages
    - [x] In classes
    - [x] In methods
    - [x] In functions
    - [x] Before classes
    - [x] Before functions
    - [x] Before methods
    - [x] Before global
    - [x] Before ivar
    - [x] Before locale
    - [x] After classes
    - [x] After functions
    - [x] After methods
    - [x] After global
    - [x] After ivar
    - [x] After locale
- [ ] Imports
  - [x] Imports that are not at the beginning of the container 
  - [x] Clean duplication between the two import resolution classes
  - [x] Refactor visit code of the imports that is currently not so clean
  - [x] Have two imports identical should still produce two imports
  - [x] Source anchor
  - [x] Test import of a sub package that has the same name as a class contained in the same package
  - [ ] See if stub packages should be UnkownImportedEntities
  - [ ] Import shadowing other entities with aliases
  - [x] Classic import
    - [x] Manage absolute paths
    - [x] Import packages
    - [x] Import modules
    - [x] From package
    - [x] From Module
    - [x] From methods
    - [x] From classes
    - [x] From functions 
    - [x] Stubs
    - [x] Two stubs of the same name produce only one stub
    - [x] Spaces in the middle of the imports
    - [x] Alias
  - [ ] Import from 
    - [x] Test import two entities with the same name (the last one declared win) 
    - [x] Test with space after the dot
    - [x] Manage relative paths
    - [x] Manage absolute paths
    - [x] Import packages
    - [x] Import modules
    - [x] Import Class
    - [x] Import functions
    - [x] Import variables
    - [x] From package
    - [x] From Module
    - [x] From methods
    - [x] From classes
    - [x] From functions
    - [x] Stubs
    - [x] Multiple Items
    - [ ] Subs with relative imports (. and ..)
    - [x] Alias
  - [ ] ImportLib/\_\_import\_\_
    - [ ] Manage relative paths
    - [ ] Manage absolute paths
    - [ ] Import packages
    - [ ] Import modules
    - [ ] Import Class
    - [ ] Import functions
    - [ ] Import variables
    - [ ] From package
    - [ ] From Module
    - [ ] From methods
    - [ ] From classes
    - [ ] From functions
    - [ ] Stubs
- [ ] Functions
  - [x] Name
  - [ ] Stub
  - [x] In module
  - [x] In Package
  - [x] In Function
  - [x] Source anchor
  - [x] Singature
  - [ ] Two functions with the same name but different parameters
  - [ ] Two functions with the same name but different parents
  - [ ] A function shadowing another function in the same parent of the same name
  - [ ] Two stubs of the same name
- [ ] Local variables in Functions
  - [x] Name
  - [x] Source Anchor
  - [x] Multiple assignations creates only one var
  - [x] Two local variables with the same name but different parents
  - [ ] Assignation of multiple variables
  - [x] Tuple assignations
- [ ] Methods
  - [x] Name
  - [x] Parent
  - [x] Signature
  - [x] Constructor
  - [x] Getters and Setters
  - [ ] Getters and Setters using @property
  - [x] Anchor
  - [ ] Stub 
  - [ ] CC
  - [ ] Two methods with the same name but different parameters
  - [ ] Two methods with the same name but different parents
  - [ ] Two stubs of the same name
  - [ ] Shadowed methods
  - [ ] First paramater is not called self
- [ ] Local variables in Methods
  - [x] Name
  - [x] Source Anchor
  - [x] Multiple assignations creates only one var
  - [x] Two local variables with the same name but different parents
  - [ ] Assignation of multiple variables
  - [x] Tuple assignations
- [ ] Classes
  - [x] Name
  - [x] In package
  - [x] In module
  - [x] In function
  - [x] In method?
  - [x] In class?
  - [ ] Stub 
  - [ ] Exceptions
  - [x] Superclasses
  - [ ] Superclass when not defined
  - [ ] Metaclasses
  - [x] Classes in functions
  - [x] Two classes with the same name but different parents
  - [x] Shadowed classes
  - [ ] Two stubs of the same name
- [x] Metaclass
- [ ] Metaclass usage
  - [x] Normal
  - [ ] Metaclass from import
  - [ ] Metaclass from from import
  - [x] Source anchor  
  - [x] Stub
- [ ] Instance variables
  - [x] In __init__
  - [x] Not in __init__
  - [ ] Defined outside the class ?? Question for Anne and Nicolas
  - [x] Only first assignation creates ivar
  - [ ] stub
  - [ ] Two stubs of the same name
  - [x] source anchor
  - [x] name
  - [x] Two instance variables with the same name but different parents
  - [x] Multiple assignations creates only one var
  - [ ] Assignation of multiple variables
  - [x] Tuple assignations
- [ ] Class variables 
  - [ ] stub
  - [ ] Two stubs of the same name
  - [x] At the beginning
  - [x] In the middle
  - [ ] Defined outside the class ?? Question for Anne and Nicolas
  - [x] Only first assignation creates cvar
  - [x] source anchor
  - [x] name
  - [x] Two class variables with the same name but different parents
  - [x] Multiple assignations creates only one var
  - [ ] Assignation of multiple variables
  - [x] Tuple assignations
- [ ] Parameters 
  - [ ] Two parameters with the same name but different parents
  - [ ] default value
  - [ ] Manage * (tagging parameters after that like to be explicitly named)
  - [ ] Manage / or \ (to check)
  - [ ] Manage variadic parameters
  - [ ] Manage *_
- [ ] Global Variables
  - [x] Name 
  - [x] Source anchor
  - [x] Two global variables with the same name but different parents
  - [ ] Assignation of multiple variables
  - [x] Multiple assignations creates only one var
  - [x] Tuple assignations
  - [ ] Test that if a global get shadowed, we create a new one if we assign it again
- [ ] Decorators 
- [ ] Accesses
  - [x] Simple
  - [ ] Source anchor
  - [ ] In inner functions
  - [ ] Check if we can have embeded assignations (x = y = 2)
  - [ ] Entity that got shadowed
  - [x] From from import
  - [ ] From import
  - [x] From import with Alias
  - [ ] Do not take into account imports that are after the entity to resolve
  - [x] With a shadowed entity checking the right one is selected
  - [ ] Do not take into account shadowed imports
  - [x] Stub
  - [ ] Default values of parameters?
  - [x] Write access with a tuple in the assignation
  - [ ] Write access that is not the first writing
  - [ ] Read
    - [x] From package
    - [x] From module
    - [x] From function
    - [x] From lambda
    - [ ] From Class
    - [x] From method
    - [x] To global
    - [ ] To ivar
    - [ ] To cvar
    - [ ] To ivar outside the class
    - [ ] To cvar outside the class
    - [x] To local var 
    - [x] To parameter
  - [x] Write
    - [x] From package
    - [x] From module
    - [x] From function
    - [x] From lambda
    - [x] From Class
    - [x] From method
    - [x] To global
    - [x] To ivar
    - [x] To cvar
    - [x] To local var 
- [ ] Invocations
  - [ ] Entity that got shadowed
  - [ ] From import
  - [ ] From from import
  - [ ] From import with Alias
  - [ ] With a shadowed entity checking the right one is selected
  - [ ] Do not take into account shadowed imports
  - [ ] Stub
  - [ ] Do not take into account imports that are after the entity to resolve
  - [ ] Signature
- [ ] References
  - [ ] Entity that got shadowed
  - [ ] From import
  - [x] From from import
  - [x] From import with Alias
  - [ ] With a shadowed entity checking the right one is selected
  - [ ] Do not take into account shadowed imports
  - [ ] Do not take into account imports that are after the entity to resolve
  - [x] Stub
  - [x] Source anchor
  - [x] From
    - [x] Package
    - [x] Module
    - [x] Class
    - [x] Function
    - [x] Method
    - [x] Lambda 
  - [ ] To
    - [x] Package
    - [x] Class
    - [x] Module
    - [x] Function
    - [ ] Method
- [ ] Instanciations
  - [ ] Stub
  - [x] Package
  - [x] Module
  - [x] Class
  - [x] Function
  - [x] Method
  - [x] Lambda 
- [ ] Inheritance
  - [ ] Entity that got shadowed
  - [x] Subclass
  - [x] Superclass
  - [ ] From import
  - [x] From from import
  - [ ] From import with Alias
  - [ ] Do not take into account imports that are after the entity to resolve
  - [ ] With a shadowed entity checking the right one is selected
  - [ ] Do not take into account shadowed imports
  - [ ] Stub
- [ ] Primitive types
- [ ] Manage "global" keyword
- [ ] Manage "nonlocal" keyword
- [ ] Structures
- [ ] Variables with a star? Pointer? Please no
- [ ] Tuples assignations
- [ ] Lambdas
  - [x] Lambda in lambda
  - [x] Signature
  - [ ] Parameters
  - [x] Lambda in classes
  - [x] Lambda in Modules
  - [x] Lambda in Packages
  - [x] Lambda in functions
  - [x] Lambda in methods
  - [x] Lambda in lambdas
  - [x] Source anchor
- [ ] Generic types
- [ ] Shadowing
  - [x] Function shadowing function
  - [x] Class shadowing class
  - [ ] Import shadowing import
  - [ ] Import alias shadowing import alias
  - [ ] Method shadowing method
  - [ ] Temporary shadowing temporary
  - [ ] Class variable shadowing class variable
  - [x] Function shadowing class
  - [ ] Function shadowing global
  - [ ] Function shadowing import
  - [ ] Function shadowing import alias
  - [ ] Function shadowing method
  - [ ] Function shadowing temporary
  - [ ] Function shadowing class variable
  - [x] Class shadowing function
  - [ ] Class shadowing global
  - [ ] Class shadowing import
  - [ ] Class shadowing import alias
  - [ ] Class shadowing method
  - [ ] Class shadowing temporary
  - [ ] Class shadowing class variable
  - [ ] Global shadowing import
  - [ ] Global shadowing import alias
  - [ ] Global shadowing method
  - [ ] Global shadowing temporary
  - [ ] Global shadowing class variable
  - [ ] Import shadowing import alias
  - [ ] Import shadowing method
  - [ ] Import shadowing temporary
  - [ ] Import shadowing class variable
  - [ ] Import alias shadowing method
  - [ ] Import alias shadowing temporary
  - [ ] Import alias shadowing class variable
  - [ ] Method shadowing temporary
  - [ ] Method shadowing class variable
  - [ ] Temporary shadowing class variable
- [x] Manage Assignment expression
- [ ] Check aliases with all kind of associations
- [ ] Refactor setting the symbol resolution of superclasses from #createClass: to #visitSuperclass:
- [x] Ensure we have no nil source/target in associations

I'll add thing little by little
